# Generated by Django 4.1 on 2023-09-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.EmailField(max_length=100)),
                ('author', models.CharField(max_length=13)),
                ('slug', models.CharField(max_length=150)),
                ('timeStamp', models.DateField(blank=True)),
            ],
        ),
    ]
