# Generated by Django 4.1 on 2023-09-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usercontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userContact',
        ),
    ]
